# 应用名称
spring:
  application:
    name: eureka_server
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    # 是否注册
    register-with-eureka: false
    # 是否检索服务
    fetch-registry: true
    # 列出所有可用注册中心的地址
    service-url:
      defaultZone:  http://${eureka.instance.hostname}:8086/eureka/
server:
  port: 8086
